language: none

sudo: required

dist: trusty

git:
  depth: false

addons:
  sonarcloud: true
  apt:
    sources:
     - sourceline: 'deb http://download.mono-project.com/repo/ubuntu trusty main'
       key_url: 'http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF'
    packages:
     - mono-complete

jdk:
  - openjdk11

before_install: 
  - wget -O os.deb http://oscript.io/downloads/1_0_21/deb
  - sudo dpkg -i os.deb; sudo apt install -f
  - oscript
  - curl -L https://github.com/asosnoviy/1testrunner/releases/download/1.7.1-alpha/1testrunner-1.7.1_alpha.ospx > 1testrunner.ospx

install: 
  - sudo opm install
  - sudo opm install -f ./1testrunner.ospx
  - sudo opm install reflector

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

script:
  - ./travis.sh 
