name: QA

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0

    - name: Setup Onescript Action
      uses: otymko/setup-onescript@v1.1
      with:
        version: 1.5.0

    - name: Install dependencies
      run: |
        opm install opm@1.0.2
        opm install -l --dev

    
    - name: Compute branch name
      uses: nelonoel/branch-name@v1.0.1
    
    - name: Извлечение версии пакета
      shell: bash
      run: echo "##[set-output name=version;]`cat packagedef | grep ".Версия(" | sed 's|[^"]*"||' | sed -r 's/".+//'`"
      id: extract_version

    - name: Run tests
      run: |
        oscript ./tasks/coverage.os

    - name: SonarCloud Scan on push
      if:  github.repository == 'nixel2007/moskito' && github.event_name == 'push'
      uses: nixel2007/sonarcloud-github-action@v1.4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.host.url=https://sonar.openbsl.ru
          -Dsonar.branch.name=${{ env.BRANCH_NAME }}
          -Dsonar.projectVersion=${{ steps.extract_version.outputs.version }}
           
    - name: SonarCloud Scan on PR
      if: github.repository == 'nixel2007/moskito' && github.event_name == 'pull_request'
      uses: nixel2007/sonarcloud-github-action@v1.4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.host.url=https://sonar.openbsl.ru
          -Dsonar.pullrequest.key=${{ github.event.pull_request.number }}
          -Dsonar.pullrequest.branch=${{ github.event.pull_request.head.ref }}
          -Dsonar.pullrequest.base=${{ github.event.pull_request.base.ref }}
          -Dsonar.scm.revision=${{ github.event.pull_request.head.sha }}
